[project]
name = "pyfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.13.0",
    "paramiko>=3.5.0",
    "pydantic>=2.10.1",
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
]
